export const SIGNUP = 'SIGNUP';
export const SIGNIN = 'SIGNIN';
export const SIGNOUT = 'SIGNOUT';

export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_ONE_PRODUCT = 'FETCH_ONE_PRODUCT';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

export const ADD_ADDRESS = 'ADD_ADDRESS';
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const REMOVE_ADDRESS = 'REMOVE_ADDRESS';
export const FETCH_ADDRESS = 'FETCH_ADDRESS';

export const API_ERROR_404 = 'API_ERROR_404';
export const API_ERROR_500 = 'API_ERROR_500';

export const FETCH_CUSTOMER_SERVICE = 'FETCH_CUSTOMER_SERVICE';
